### PR TITLE
Unity package

### PR DESCRIPTION
**Pull request by AlonTalmi**
Unity users will be able to install Jab by importing:
https://github.com/pakrym/jab.git?path=src/Jab.Unity/Package

Tested with my fork's branch at URL:
https://github.com/AlonTalmi/jab.git?path=src/Jab.Unity/Package#UnityNpmPackage

(In Unity: Window ↝ Package Manager ↝ '+' ↝ Add package from git URL...)

I already added package.json, Dlls and meta files, until you decide to rename one of the packages this should be enough.
Do notice that *.meta files are ignored in your .gitignore, I forcefully tracked them, but maybe it would be a better idea to make a .gitignore exceptions for them?

As for the build process, I don't have a lot of experience, help will be appreciated @pakrym

Edit: I understood I might have confused you, I created an npm package using npm init, but we don't actually need to upload the package to npm, it's just the structure Unity uses, it will works straight from this repository.
If you merge this PR it's enough to be installable through Unity, we just need to make sure newly built dlls are copied to the package directory

### CODE REVIEW

**Comment by pakrym** [comment]
Will it be easier for users if we do upload it to NPM? We'd still need some automation to keep dll files updated so might as well publish the full package?

**Comment by pakrym** [comment]
Are you able to install https://www.npmjs.com/package/com.pakrym.jab ?

**Comment by pakrym** [comment]
Navigate to the Packages directory of your project.
Adjust the [project manifest file](https://docs.unity3d.com/Manual/upm-manifestPrj.html) manifest.json in a text editor.
Ensure https://registry.npmjs.org/ is part of scopedRegistries.
Ensure com.pakrym is part of scopes.
Add com.pakrym.jab to the dependencies, stating the latest version.
A minimal example ends up looking like this. Please note that the version X.Y.Z stated here is to be replaced with [the latest released version](https://www.npmjs.com/package/com.pakrym.jab), which is currently NPM Package.

{
  "scopedRegistries": [
    {
      "name": "npmjs",
      "url": "https://registry.npmjs.org/",
      "scopes": [
        "com.pakrym"
      ]
    }
  ],
  "dependencies": {
    "com.pakrym.jab": "X.Y.Z",
    ...
  }
}

**Comment by AlonTalmi** [comment]
Your setup works and I successfully installed the package,
From my experience, most users would prefer just installing using UPM with a git URL as it's faster.
But installing a scoped registry has some pros, like selecting a specific version, see when a new version released and see all packages created under the com.pakrym registry all straight from the Unity editor (I can take some screenshots to show you what it looks like)

But if you want to create your own registry for the Unity package I'll suggest checking out [OpenUPM](https://openupm.com/) it has a Unity specific package library, package discovery and CLI tools

**Comment by pakrym** [comment]
If you don't mind, let's start with an NPM package. Keeping binaries up-to-date in git is a bit tricky and grows the repo size. I'll think about automating github url publishing in the meantime.

**Comment by AlonTalmi** [comment]
Np, let me know if I can help :)
But do know you'll need another meta file for the Readme file, and every file or directory you'll add to the package in the future

**Comment by pakrym** [comment]
> But do know you'll need another meta file for the Readme file, and every file or directory you'll add to the package in the future

TIL :) 

Do you mind helping me out with that and pushing a meta file for README into this PR?

**Comment by pakrym** [comment]
Thank you so much for your help @AlonTalmi !

**Pull request merged**
